-- ===================================================
-- MASTERKOTLOV SUPABASE DATABASE SCHEMA & SEED SCRIPT
-- ===================================================

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    desk TEXT NOT NULL,
    description TEXT,
    top BOOLEAN DEFAULT FALSE,
    images TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Service Requests / Orders Table
CREATE TABLE IF NOT EXISTS public.service_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    problem_description TEXT NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'in_progress', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for Products
-- Public read access (anyone can view products)
DROP POLICY IF EXISTS "Public read products" ON public.products;
CREATE POLICY "Public read products" ON public.products
    FOR SELECT USING (true);

-- Authenticated admins can create, update, delete products
DROP POLICY IF EXISTS "Admin full control products" ON public.products;
CREATE POLICY "Admin full control products" ON public.products
    FOR ALL USING (auth.role() = 'authenticated');

-- 5. RLS Policies for Service Requests
-- Anyone can submit a service request / order
DROP POLICY IF EXISTS "Public insert service requests" ON public.service_requests;
CREATE POLICY "Public insert service requests" ON public.service_requests
    FOR INSERT WITH CHECK (true);

-- Authenticated admins can read, update, delete service requests
DROP POLICY IF EXISTS "Admin full control service requests" ON public.service_requests;
CREATE POLICY "Admin full control service requests" ON public.service_requests
    FOR ALL USING (auth.role() = 'authenticated');

-- 6. Setup Supabase Storage Bucket for Product Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images" ON storage.objects
    FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admin Upload Product Images" ON storage.objects;
CREATE POLICY "Admin Upload Product Images" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'product-images' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin Delete Product Images" ON storage.objects;
CREATE POLICY "Admin Delete Product Images" ON storage.objects
    FOR DELETE USING (bucket_id = 'product-images' AND auth.role() = 'authenticated');

-- 7. Seed Initial Product Data (All 19 Products with Complete Image Arrays)
INSERT INTO public.products (id, name, price, desk, top, images) VALUES
(1, 'Հոսքի սենսոր', '18000-25000 դրամ', 'Վերահսկում է ջրի հոսքը կաթսայի համակարգում և ապահովում սարքի ճիշտ աշխատանքը տաք ջրի օգտագործման ժամանակ։', true, ARRAY['/parts/1/photo_2026-09-24_22-10-10.jpg', '/parts/1/photo_2026-09-24_22-10-11 (2).jpg', '/parts/1/photo_2026-09-24_22-10-11.jpg', '/parts/1/photo_2026-09-24_22-10-12.jpg', '/parts/1/photo_2026-09-24_22-10-13 (2).jpg', '/parts/1/photo_2026-09-24_22-10-13.jpg', '/parts/1/photo_2026-09-24_22-10-14.jpg', '/parts/1/photo_2026-09-24_22-10-15.jpg']),
(2, 'Նասոս', '45000-85000 դրամ', 'Ապահովում է ջրի մշտական շրջանառությունը ջեռուցման համակարգում՝ պահպանելով արդյունավետ ջերմափոխանակությունը։', true, ARRAY['/parts/2/photo_2026-09-24_22-10-33 (2).jpg', '/parts/2/photo_2026-09-24_22-10-33.jpg', '/parts/2/photo_2026-09-24_22-10-34.jpg']),
(3, 'Պանտուս', '18000 դրամ', 'Կաթսայի հիդրավլիկ համակարգի կարևոր բաղադրիչ, որը նպաստում է ջրի հոսքի և ճնշման կայուն աշխատանքին։', true, ARRAY['/parts/3/photo_2026-09-24_22-10-45.jpg', '/parts/3/photo_2026-09-24_22-10-46.jpg', '/parts/3/photo_2026-09-24_22-10-47.jpg']),
(4, 'Պլատայի Վերանորոգում', '25000 դրամ', 'Էլեկտրոնային կառավարման պլատայի ախտորոշում և վերանորոգում՝ սարքի անխափան աշխատանքը վերականգնելու համար։', true, ARRAY['/parts/4/photo_2026-09-24_22-11-02.jpg']),
(5, 'Եռակողմ Փականի Շարժիչ', '25000 դրամ', 'Կառավարում է եռակողմ փականի դիրքը՝ ջեռուցման և տաք ջրի ռեժիմների միջև անցումն ապահովելու համար։', true, ARRAY['/parts/5/photo_2026-09-24_22-11-34.jpg']),
(6, 'Երկրորդական Ջերմափոխանակիչ', '50000 դրամ', 'Ապահովում է կենցաղային տաք ջրի արդյունավետ տաքացումը՝ ջերմությունը փոխանցելով առաջնային համակարգից։', true, ARRAY['/parts/6/photo_2026-09-24_22-11-18.jpg']),
(7, 'Ճնշման Սենսոր', '18000-23000 դրամ', 'Չափում և վերահսկում է համակարգի ճնշումը՝ կանխելով վթարային իրավիճակները։', true, ARRAY['/parts/7/photo_2026-09-24_22-11-48 (2).jpg', '/parts/7/photo_2026-09-24_22-11-48.jpg', '/parts/7/photo_2026-09-24_22-11-49.jpg']),
(8, 'Օդի Սենսոր', '25000 դրամ', 'Վերահսկում է օդի հոսքը և նպաստում այրման գործընթացի անվտանգ ու արդյունավետ աշխատանքին։', true, ARRAY['/parts/8/photo_2026-09-24_22-12-00.jpg']),
(9, 'Ճնշման Ցուցիչ', '18000 դրամ', 'Ցուցադրում է համակարգի ընթացիկ ճնշումը՝ հեշտացնելով վերահսկումն ու սպասարկումը։', true, ARRAY['/parts/9/photo_2026-09-24_22-12-08.jpg']),
(10, 'Օդամղիչ', '45000-65000 դրամ', 'Ապահովում է անհրաժեշտ օդամատակարարումը և ծխագազերի հեռացումը այրման խցիկից։', true, ARRAY['/parts/10/photo_2026-09-24_22-12-19.jpg']),
(11, 'Գազի Փական', '30000-65000 դրամ', 'Կարգավորում և վերահսկում է գազի մատակարարումը՝ ապահովելով անվտանգ և կայուն այրում։', true, ARRAY['/parts/11/photo_2026-09-24_22-12-31.jpg']),
(12, 'Այրման Մոմիկ', '13000-18000 դրամ', 'Ստեղծում է կայծ՝ գազի այրումը մեկնարկելու և այրիչի աշխատանքը ապահովելու համար։', true, ARRAY['/parts/12/photo_2026-09-24_22-12-41.jpg', '/parts/12/photo_2026-09-24_22-12-44.jpg']),
(13, 'Ռոտոր', '25000-30000 դրամ', 'Պոմպի շարժական տարր, որը պատասխանատու է ջրի արդյունավետ շրջանառության համար։', true, ARRAY['/parts/13/photo_2026-09-24_22-12-56.jpg']),
(14, 'Հիդրողումբ', '25000-90000 դրամ', 'Հիդրավլիկ հանգույց, որը բաշխում և կարգավորում է ջրի հոսքը կաթսայի տարբեր հատվածներում։', true, ARRAY['/parts/14/photo_2026-09-24_22-13-02.jpg', '/parts/14/photo_2026-09-24_22-13-03.jpg', '/parts/14/photo_2026-09-24_22-13-04.jpg']),
(15, 'Ջերմափոխանակիչ', '75000-105000 դրամ', 'Կաթսայի հիմնական բաղադրիչներից մեկը, որը փոխանցում է ջերմությունը այրման համակարգից ջրին։', true, ARRAY['/parts/15/photo_2026-09-24_22-13-17.jpg', '/parts/15/photo_2026-09-24_22-13-18 (2).jpg', '/parts/15/photo_2026-09-24_22-13-18.jpg', '/parts/15/photo_2026-09-24_22-13-19 (2).jpg', '/parts/15/photo_2026-09-24_22-13-19.jpg']),
(16, 'Լրացման Փական', '18000-23000 դրամ', 'Օգտագործվում է համակարգում ջուր ավելացնելու և անհրաժեշտ ճնշումը վերականգնելու համար։', true, ARRAY['/parts/16/photo_2026-09-24_22-13-31 (2).jpg', '/parts/16/photo_2026-09-24_22-13-31.jpg', '/parts/16/photo_2026-09-24_22-13-32 (2).jpg', '/parts/16/photo_2026-09-24_22-13-32.jpg', '/parts/16/photo_2026-09-24_22-13-33.jpg']),
(17, 'Անվտանգության Փական', '18000 դրամ', 'Պաշտպանում է համակարգը գերճնշումից՝ ավտոմատ կերպով բացվելով անհրաժեշտության դեպքում։', true, ARRAY['/parts/17/photo_2026-09-24_22-13-48 (2).jpg', '/parts/17/photo_2026-09-24_22-13-48.jpg', '/parts/17/photo_2026-09-24_22-13-49.jpg']),
(18, 'Եռակողմ Փական', '25000-30000 դրամ', 'Բաշխում է ջրի հոսքը ջեռուցման և տաք ջրի համակարգերի միջև՝ ըստ պահանջի։', true, ARRAY['/parts/18/photo_2026-09-24_22-13-59.jpg', '/parts/18/photo_2026-09-24_22-14-00 (2).jpg', '/parts/18/photo_2026-09-24_22-14-00.jpg', '/parts/18/photo_2026-09-24_22-14-01 (2).jpg', '/parts/18/photo_2026-09-24_22-14-01.jpg']),
(19, 'Ընդարձակման Բաք', '45000-55000 դրամ', 'Փոխհատուցում է ջրի ծավալի փոփոխությունները տաքացման ընթացքում՝ պահպանելով համակարգի կայուն ճնշումը։', true, ARRAY['/parts/19/photo_2026-09-24_22-14-19 (2).jpg', '/parts/19/photo_2026-09-24_22-14-19.jpg', '/parts/19/photo_2026-09-24_22-14-20.jpg', '/parts/19/photo_2026-09-24_22-14-21.jpg'])
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    desk = EXCLUDED.desk,
    top = EXCLUDED.top,
    images = EXCLUDED.images;

-- Adjust identity sequence
SELECT setval('products_id_seq', (SELECT MAX(id) FROM public.products));
