const fs = require('fs');
const path = require('path');

const products = JSON.parse(fs.readFileSync('./data/products.json', 'utf8'));
const root = './images/products';

const fullProducts = products.map((p) => {
	const dir = path.join(root, String(p.id));
	let images = [];
	if (fs.existsSync(dir)) {
		const files = fs.readdirSync(dir).filter((f) => !f.startsWith('.'));
		files.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
		images = files.map((f) => `/parts/${p.id}/${f}`);
	}
	const priceClean = String(p.price || '').replace(/\s*դրամ|\s*Դրամ/g, '').trim();
	return { id: p.id, name: p.name, price: priceClean, desk: p.desk, top: p.top, images };
});

const valuesSql = fullProducts
	.map((p) => {
		const imagesArraySql = 'ARRAY[' + p.images.map((img) => `'${img.replace(/'/g, "''")}'`).join(', ') + ']';
		const nameSql = `'${p.name.replace(/'/g, "''")}'`;
		const priceSql = `'${p.price.replace(/'/g, "''")}'`;
		const deskSql = `'${p.desk.replace(/'/g, "''")}'`;
		return `(${p.id}, ${nameSql}, ${priceSql}, ${deskSql}, ${p.top ? 'true' : 'false'}, ${imagesArraySql})`;
	})
	.join(',\n');

const schemaContent = `-- ===================================================
-- MASTERKOTLOV SUPABASE DATABASE SCHEMA & SEED SCRIPT
-- ===================================================

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    desk TEXT NOT NULL,
    description TEXT,
    top BOOLEAN DEFAULT FALSE,
    images TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Service Requests / Orders Table
CREATE TABLE IF NOT EXISTS public.service_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    problem_description TEXT NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'in_progress', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Finance Ledger Table
CREATE TABLE IF NOT EXISTS public.finance_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID REFERENCES public.service_requests(id) ON DELETE SET NULL,
    amount NUMERIC NOT NULL,
    client_name TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Admin Users Table
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies (Open Read/Write for Client App Integration)
DROP POLICY IF EXISTS "Allow all for products" ON public.products;
CREATE POLICY "Allow all for products" ON public.products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for service requests" ON public.service_requests;
CREATE POLICY "Allow all for service requests" ON public.service_requests FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for finance ledger" ON public.finance_ledger;
CREATE POLICY "Allow all for finance ledger" ON public.finance_ledger FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for admin users" ON public.admin_users;
CREATE POLICY "Allow all for admin users" ON public.admin_users FOR ALL USING (true) WITH CHECK (true);

-- 7. Setup Supabase Storage Bucket for Product Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS Policies
DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images" ON storage.objects FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Upload Product Images" ON storage.objects;
CREATE POLICY "Public Upload Product Images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Delete Product Images" ON storage.objects;
CREATE POLICY "Public Delete Product Images" ON storage.objects FOR DELETE USING (bucket_id = 'product-images');

-- 8. Seed Initial Admin User
INSERT INTO public.admin_users (name, username, email, status) VALUES
('Գոռ', 'admin', 'admin@masterkotlov.am', 'active')
ON CONFLICT (username) DO NOTHING;

-- 9. Seed Initial Product Data (Raw prices without ' դրամ')
INSERT INTO public.products (id, name, price, desk, top, images) VALUES
${valuesSql}
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    desk = EXCLUDED.desk,
    top = EXCLUDED.top,
    images = EXCLUDED.images;

-- Adjust identity sequence
SELECT setval('products_id_seq', (SELECT MAX(id) FROM public.products));
`;

fs.writeFileSync('./supabase/schema.sql', schemaContent, 'utf8');
console.log('Updated supabase/schema.sql with admin_users and cleaned prices!');
